- name: Download appliance
  unarchive:
    src: http://download.libguestfs.org/binaries/appliance/appliance-1.46.0.tar.xz
    remote_src: yes
    dest: /tmp
  args:
    creates: /tmp/appliance

- set_fact:
    virt_customize_env:
      LIBGUESTFS_PATH: '/tmp/appliance'
      LIBGUESTFS_BACKEND: 'direct'
