#!/bin/sh -ex

mkdir /home/zuul-worker/.docker
cat /tmp/in_target.d/docker-credentials.json >> /home/zuul-worker/.docker/config.json
chmod 0600 /home/zuul-worker/.docker/config.json
chown -R zuul-worker:zuul-worker /home/zuul-worker/.docker
