#!/bin/sh -ex

apt-get update

# python3-apt is required for bindep in tox ansible job
apt-get install -y \
    ansible \
    cron \
    curl \
    equivs \
    git \
    jq \
    lintian \
    lsof \
    make \
    python3-apt \
    python3-dev \
    python3-pip \
    python3-venv \
    sed \
    tar \
    unzip

# Create global virtualenv to avoid conflict with apt packages
python3 -m venv /opt/global-venv
source /opt/global-venv/bin/activate
pip install tox
ln -s /opt/global-venv/bin/tox /usr/local/bin/tox

systemctl enable cron
