#!/bin/sh -ex

apt-get update

# python3-apt is required for bindep in tox ansible job
# python3-docker is required to build sibling mock docker images
apt-get install -y \
    ansible \
    cron \
    curl \
    equivs \
    git \
    jq \
    lintian \
    lsof \
    make \
    python3-apt \
    python3-dev \
    python3-docker \
    python3-venv \
    sed \
    tar \
    unzip


apt-get install -y pipx
# Bookworm use pipx 1.1 which doesn't have --global flag
# For Trixie, 'pipx --global' can be used instead of variables
PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin pipx install tox

systemctl enable cron
