#!/bin/sh -ex

apt-get update

apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    apparmor \
    apparmor-utils

curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

apt-get update

apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

systemctl enable docker

# Compatibility until we migrate to docker compose (without hyphen) everywhere
ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

# No service running in chroot
# systemctl start docker
# docker version

docker compose version

# Script must run after zuul-worker & wazo-debug users creation, hence named 60-
usermod -a -G docker wazo-debug
usermod -a -G docker zuul-worker
