#!/bin/sh -ex

mkdir -p /home/zuul-worker/.docker
chown zuul-worker: /home/zuul-worker/.docker
chmod 0700 /home/zuul-worker/.docker


cat /tmp/in_target.d/docker-credentials.json >> /home/zuul-worker/.docker/config.json
chmod 0600 /home/zuul-worker/.docker/config.json
