#!/bin/sh -ex

mkdir -p /home/zuul-worker/.ssh
chown zuul-worker: /home/zuul-worker/.ssh
chmod 0700 /home/zuul-worker/.ssh

ssh-keyscan github.com >>/home/zuul-worker/.ssh/known_hosts
chown zuul-worker: /home/zuul-worker/.ssh/known_hosts
chmod 0600 /home/zuul-worker/.ssh/known_hosts
