#!/bin/sh -ex
# This is a temporary fix to workaround the pod-debian-11 build error
apt-get update
apt-get install -y \
        black \
        git \
        iproute2 \
        python3-apt \
        python3-bashate \
        python3-doc8 \
        python3-flake8 \
        python3-pip \
        python3-setuptools \
        python3-virtualenv \
        rsync \
        sudo \
        traceroute \
        wget \
        yamllint
