#!/bin/sh -ex

mkdir -p /etc/systemd/system/sshd.service.d

cat > /etc/systemd/system/sshd.service.d/override.conf << EOF
[Unit]
After=network.target auditd.service systemd-user-sessions.service
EOF

systemctl daemon-reload
